import '@/app/global.css'
import { Suspense } from 'react'

export const metadata = {
  title: 'Sistem Rekomendasi Film',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
